In [1]:
import numpy as np

In [2]:
#Create a 3x3x3 array with random values
np.random.rand(3,3)

array([[0.43972593, 0.01985018, 0.30691575],
       [0.79181442, 0.43488207, 0.53286373],
       [0.40869175, 0.35740272, 0.58991291]])

In [8]:
#How to get the dates of yesterday, today and tomorrow?
from datetime import date

today = date.today()
print("Today's date:", today)

import datetime
today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)

print(yesterday)

tom = today + datetime.timedelta(days=1)
print(tom)

Today's date: 2020-07-27
2020-07-26
2020-07-28


In [15]:
import numpy as np
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)

x[1::2,::2] = 1
x[::2,1::2] = 1
#print(x)
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
#How to find common values between two arrays?
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

print(np.intersect1d(a,b))

[4 5]


In [22]:
#Consider two random array A and B, check if they are equal
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

print(arr1)
print(arr2)

print(arr1== arr2)

[[0.39692008 0.87836301 0.69877421]
 [0.89159844 0.61859782 0.21434761]
 [0.23932969 0.73479086 0.35614564]]
[[0.95137709 0.59519736 0.46822169]
 [0.34480524 0.15963784 0.80042601]
 [0.84339541 0.14653502 0.0630797 ]]
[[False False False]
 [False False False]
 [False False False]]


In [23]:
#How to get the diagonal of a dot product?

i = np.array([[1,2],[3,4]])
v=np.array([9,10])

print (i.dot(v))

[29 67]


In [24]:
#13.How to find the most frequent value in an array?
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[1 6 5 5 1 0 4 7 1 0 3 8 2 4 8 2 3 7 6 6 7 8 6 6 9 6 4 5 7 9 6 3 3 1 8 9 1
 8 9 3]
Most frequent value in the above array:
6


In [37]:
#How to print all the values of an array?
i = np.array([[1,2,11],[3,4,10],[4,5,6]])
print(i)

#print ('Max Value is ',i.max())

print(i.shape)

for x in (range(i.shape[0])):
    print('Values in ',x,' row')
    for y in (range(i.shape[1])):
              print (i[x][y])

[[ 1  2 11]
 [ 3  4 10]
 [ 4  5  6]]
11
(3, 3)
Values in  0  row
1
2
11
Values in  1  row
3
4
10
Values in  2  row
4
5
6


In [38]:
#Normalize a 5x5 random matrix
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.05151324 0.79539702 0.45797676 0.26814503 0.20837407]
 [0.33930864 0.77769174 0.97652174 0.38212336 0.74587699]
 [0.39059069 0.95261484 0.56694888 0.11675642 0.80774158]
 [0.05782734 0.86768305 0.14717716 0.97060343 0.97743504]
 [0.32337421 0.16377717 0.44899599 0.21071179 0.5504798 ]]
After normalization:
[[0.         0.80339807 0.43898256 0.23396338 0.16941046]
 [0.31082042 0.78427628 0.99901363 0.35706052 0.74991619]
 [0.36620528 0.97319407 0.55667298 0.07046294 0.81673025]
 [0.00681926 0.88146732 0.10331749 0.99262184 1.        ]
 [0.29361116 0.12124559 0.42928329 0.1719352  0.53888629]]


In [51]:
#Subtract the mean of each row of a matrix
import numpy as np
print("Original matrix:\n")
X = np.random.rand(3,3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)



Original matrix:

[[0.40948078 0.28197119 0.35422272]
 [0.54251267 0.74602955 0.70759475]
 [0.47751408 0.62116085 0.82513715]]

Subtract the mean of each row of the said matrix:

[[ 0.06092255 -0.06658704  0.00566449]
 [-0.12286632  0.08065056  0.04221577]
 [-0.16375661 -0.02010984  0.18386646]]


In [52]:
#Create random vector of size 10 and replace the maximum value by 0
import numpy as np
x= np.random.random(10)
print ("original Array")
print(x)

x[x.argmax()] = 0
print("Max value replaced by 0")
print(x)


original Array
[0.64739266 0.71648471 0.73528334 0.51020332 0.98812223 0.03587992
 0.86655433 0.08365673 0.82763666 0.55972763]
Max value replaced by 0
[0.64739266 0.71648471 0.73528334 0.51020332 0.         0.03587992
 0.86655433 0.08365673 0.82763666 0.55972763]


In [53]:
#How to get the n largest values of an array
import numpy as np
x= np.random.random(10)
print ("original Array")
print(x)

x.sort()
print("Sorted Array")
print(x)


original Array
[0.97193948 0.39767652 0.46292478 0.51038838 0.05590737 0.46232226
 0.21123979 0.21056482 0.80438928 0.16369874]
Sorted Array
[0.05590737 0.16369874 0.21056482 0.21123979 0.39767652 0.46232226
 0.46292478 0.51038838 0.80438928 0.97193948]


In [54]:
#How to create a record array from a regular array
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)


In [55]:
#Consider a given vector, how to add 1 to each element indexed by a second vector
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 1. 3. 5. 1. 2. 3. 2. 3. 6.]


In [56]:
#How to get the diagonal of a dot product 
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(A, B))


array([21, 71, 48])

In [57]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
